### ISSUE TITLE
Return the original error message

### ISSUE THREAD

**Issue by gaborremenyi** [fusepoolP3/p3-transformer-client-library#3]
It would be helpful to see the original error message, returned by the transformer that was invoked by the pipeline. For now it only returns an HTTP 500 when internal error occurs without any explanation.
https://github.com/fusepoolP3/p3-transformer-client-library/blob/master/src/main/java/eu/fusepool/p3/transformer/client/TransformerClientImpl.java#L157

**Comment by retog** [comment]
What do you mean by "it returs an HTTP 500". This is a java library, so how are the response codes returned?

**Comment by gaborremenyi** [comment]
What I meant was that when there is an exception in a transformer it usually returns some error message, which is lost when you return throw the unexpected response code runtime exception. I was just wandering if there is a way to return somehow that error message. If it is not possible please ignore and close this issue.

**Comment by retog** [comment]
Ok, I get it. Maybe throw a subclass of RuntimeException that has an additional method returning the response body?

**Comment by gaborremenyi** [comment]
Yes, I was thinking something like similar, so if you can do that, that would be great. Thanks
